In [2]:
import numpy as np

In [9]:
# create a one-dimensional array with alias as np and perform the following methods:
# np.Zero()

zero_array = np.zeros(7)
print(zero_array)

[0. 0. 0. 0. 0. 0. 0.]


In [10]:
# np Ones

ones_array = np.ones(7)
print(ones_array)

[1. 1. 1. 1. 1. 1. 1.]


In [13]:
# empty 

empty_array = np.empty(7)
print(empty_array)

[1. 1. 1. 1. 1. 1. 1.]


In [14]:
# arange : generates numbers for the array

arange_array = np.arange(8)
print(arange_array)

[0 1 2 3 4 5 6 7]


In [17]:
# reshape: changes the shape of the array

reshaped_array = arange_array.reshape(2,4)
print(reshaped_array)

[[0 1 2 3]
 [4 5 6 7]]


In [22]:
# linespace: separates the elements of an array evenly

linespaced_array = np.linspace(1,8,5)
print(linespaced_array)

[1.   2.75 4.5  6.25 8.  ]


In [24]:
# 2 dimesnional array

twoD_array = np.arange(16).reshape(4,4)
print(twoD_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [26]:
# 3 dimesional array

threeD_array = np.arange(27).reshape(3,3,3)
print(threeD_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [28]:
# checking the shape of an array
print(threeD_array.shape)
print(twoD_array.shape)

(3, 3, 3)
(4, 4)
