In [2]:
import numpy as np

In [8]:
# create a 1D array
oneD_array = np.array([x for x in range(1,13)])
print(oneD_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [13]:
# convert into 2D array
twoD_array = oneD_array.reshape(2,-1)
print(twoD_array)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [16]:
# convert to threeD array
threeD_array = twoD_array.reshape(2,2,-1)
print(threeD_array)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [17]:
# flatten the threeD ndarray 
flat_array = threeD_array.reshape(-1)
print(flat_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
