In [1]:
# arithmetic operations with numpy
import numpy as np

In [6]:
# create 2, diferent dimesion arrays
x = np.array([x for x in range(4)])
y = np.array([x for x in range(8)]).reshape(2,-1)

In [7]:
# addition
sum = np.add(x,y)
print(sum)

[[ 0  2  4  6]
 [ 4  6  8 10]]


In [9]:
# subtraction
sub = np.subtract(y,x)
print(sub)

[[0 0 0 0]
 [4 4 4 4]]


In [11]:
# multiplication
mult = np.multiply(x,y)
print(mult)

[[ 0  1  4  9]
 [ 0  5 12 21]]


In [13]:
# division
div = np.divide(y,x)
print(div)

[[       nan 1.         1.         1.        ]
 [       inf 5.         3.         2.33333333]]


C:\Users\Administrator\AppData\Local\Temp\ipykernel_3168\3235767940.py:2: RuntimeWarning: divide by zero encountered in divide
  div = np.divide(y,x)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_3168\3235767940.py:2: RuntimeWarning: invalid value encountered in divide
  div = np.divide(y,x)


In [14]:
# raise to a power
power2 = np.power(x,2)
print(power2)

[0 1 4 9]


In [15]:
# raise an nd array to an ndarray
ndpower = np.power(x,y)
print(ndpower)

[[   1    1    4   27]
 [   0    1   64 2187]]
