In [1]:
# working with common math and statistical functions in numpy
import numpy as np

In [39]:
arr = np.array([x for x in range(1,10)])
arr = arr.reshape(3,3)

In [19]:
np.amin(arr)
np.amin(arr,axis=1)
np.amin(arr,axis=0)

array([1, 2, 3])

In [22]:
np.amax(arr)
np.amax(arr, axis=0)
np.amax(arr, axis=1)

array([3, 6, 9])

In [23]:
np.median(arr)

5.0

In [25]:
np.mean(arr)

5.0

In [27]:
np.var(arr)

6.666666666666667

In [29]:
np.std(arr)

2.581988897471611

In [41]:
np.percentile(arr, 50)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
arr = arr.reshape(-1)
arr = np.select([arr>0], [arr * 90], default=90)
print(arr)

[ 90 180 270 360 450 540 630 720 810]


In [46]:
arr = np.sin(arr * np.pi/180)

In [48]:
np.floor(arr)

array([ 1.,  0., -1., -1.,  1.,  0., -1., -1.,  1.])

In [49]:
np.ceil(arr)

array([ 1.,  1., -1., -0.,  1.,  1., -1., -0.,  1.])