In [1]:
# working with common math and statistical functions in numpy
import numpy as np

In [2]:
arr = np.array([x for x in range(1,10)])
arr = arr.reshape(3,3)

In [3]:
np.amin(arr)
np.amin(arr,axis=1)
np.amin(arr,axis=0)

array([1, 2, 3])

In [4]:
np.amax(arr)
np.amax(arr, axis=0)
np.amax(arr, axis=1)

array([3, 6, 9])

In [5]:
np.median(arr)

5.0

In [6]:
np.mean(arr)

5.0

In [7]:
np.var(arr)

6.666666666666667

In [8]:
np.std(arr)

2.581988897471611

In [9]:
np.percentile(arr, 50)

5.0

In [10]:
arr = arr.reshape(-1)
arr = np.select([arr>0], [arr * 90], default=90)
print(arr)

[ 90 180 270 360 450 540 630 720 810]


In [11]:
arr = np.sin(arr * np.pi/180)

In [12]:
np.floor(arr)

array([ 1.,  0., -1., -1.,  1.,  0., -1., -1.,  1.])

In [13]:
np.ceil(arr)

array([ 1.,  1., -1., -0.,  1.,  1., -1., -0.,  1.])