In [2]:
# slicing and indexing of ndarrays
import numpy as np

In [4]:
oneD_array = np.array([x for x in range(1,13)])
oneD_array[-1]

12

In [6]:
twoD_array = oneD_array.reshape(2,-1)
twoD_array[-1][0]

7

In [8]:
threeD_array = twoD_array.reshape(2,2,3)
threeD_array[-1][0][2]

9

In [9]:
oneD_array[4:]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [12]:
twoD_array[-1][0:2]

array([7, 8])

In [11]:
threeD_array[-1][0][-3:-1]

array([7, 8])